name: whatsmytodaystasks
description: Shows your tasks at that day
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gradient_colors: ^1.0.0
  gradient_widgets: ^0.5.2
  jiffy: ^3.0.1
  flutter_animator: ^2.0.9
  intl: ^0.16.1
  shared_preferences: 0.5.7+3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  progress_dialog: ^1.2.4
  pull_to_refresh: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
